// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Taskmanager_MVCAPI.Data;

#nullable disable

namespace TaskmanagerMVCAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Taskmanager_MVCAPI.Models.Batch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchId"));

                    b.Property<string>("BatchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BatchId");

                    b.ToTable("Batches");

                    b.HasData(
                        new
                        {
                            BatchId = 1,
                            BatchName = "Batch1"
                        },
                        new
                        {
                            BatchId = 2,
                            BatchName = "Batch2"
                        });
                });

            modelBuilder.Entity("Taskmanager_MVCAPI.Models.NewTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<string>("AttachmentPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DueDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("DATEADD(HOUR, 24, GETDATE())");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskId");

                    b.ToTable("NewTasks");
                });

            modelBuilder.Entity("Taskmanager_MVCAPI.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.HasIndex("BatchId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            BatchId = 1,
                            StudentName = "s1b1"
                        },
                        new
                        {
                            StudentId = 2,
                            BatchId = 1,
                            StudentName = "s2b1"
                        },
                        new
                        {
                            StudentId = 3,
                            BatchId = 1,
                            StudentName = "s3b1"
                        },
                        new
                        {
                            StudentId = 4,
                            BatchId = 1,
                            StudentName = "s4b1"
                        },
                        new
                        {
                            StudentId = 5,
                            BatchId = 1,
                            StudentName = "s5b1"
                        },
                        new
                        {
                            StudentId = 6,
                            BatchId = 2,
                            StudentName = "s1b2"
                        },
                        new
                        {
                            StudentId = 7,
                            BatchId = 2,
                            StudentName = "s2b2"
                        },
                        new
                        {
                            StudentId = 8,
                            BatchId = 2,
                            StudentName = "s3b2"
                        },
                        new
                        {
                            StudentId = 9,
                            BatchId = 2,
                            StudentName = "s4b2"
                        },
                        new
                        {
                            StudentId = 10,
                            BatchId = 2,
                            StudentName = "s5b2"
                        });
                });

            modelBuilder.Entity("Taskmanager_MVCAPI.Models.TaskAssignment", b =>
                {
                    b.Property<int>("TaskAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskAssignmentId"));

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("TaskAssignmentId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskAssignments");
                });

            modelBuilder.Entity("Taskmanager_MVCAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Batch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Taskmanager_MVCAPI.Models.Student", b =>
                {
                    b.HasOne("Taskmanager_MVCAPI.Models.Batch", "Batch")
                        .WithMany("Students")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("Taskmanager_MVCAPI.Models.TaskAssignment", b =>
                {
                    b.HasOne("Taskmanager_MVCAPI.Models.Student", "Student")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("StudentId");

                    b.HasOne("Taskmanager_MVCAPI.Models.NewTask", "Task")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Taskmanager_MVCAPI.Models.Batch", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Taskmanager_MVCAPI.Models.NewTask", b =>
                {
                    b.Navigation("TaskAssignments");
                });

            modelBuilder.Entity("Taskmanager_MVCAPI.Models.Student", b =>
                {
                    b.Navigation("TaskAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
